### ISSUE TITLE
Spelling mistakes in _posts/2019-09-04-week01.md

### ISSUE THREAD

**Issue by jxuan101** [hunter-college-ossd-fall-2019/shakeel30-weekly#1]
"research" is misspelled in the paragraph on line 7.
"future" is misspelled in the paragraph on line 9.
"computer" is misspelled in the paragraph on line 9.

**Comment by jxuan101** [comment]
I fixed the issue for you and submitted a pull request. It is trivial so there shouldn't be any problems.

**Comment by shakeel30** [comment]
> "research" is misspelled in the paragraph on line 7.
> "future" is misspelled in the paragraph on line 9.
> "computer" is misspelled in the paragraph on line 9.

Thanks for the c

**Comment by shakeel30** [comment]
Thanks for the corrections and the fix.
